name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Use GitHub OIDC to authenticate with AWS
permissions:
  id-token: write
  contents: read           # Keep read at workflow level for other jobs/steps
  pull-requests: write

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    permissions:             # <--- This block is correct
      contents: write        # Grant write permission specifically for this job
      pull-requests: write   # Keep pull-requests write for commenting
      id-token: write        # Keep id-token write for AWS OIDC

    env:
      AWS_REGION: ${{ secrets.AWS_REGION || 'ap-south-1' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # Ensure full history is fetched for rebase

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::199570228070:role/oidc-demo-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -recursive

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Setup Node.js
        if: github.event_name == 'pull_request'
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install terraform-docs
        if: github.event_name == 'pull_request'
        run: |
          curl -sSLo ./terraform-docs.tar.gz https://terraform-docs.io/dl/v0.16.0/terraform-docs-v0.16.0-$(uname)-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          sudo mv terraform-docs /usr/local/bin/

      - name: Generate Terraform Docs and Commit
        if: github.event_name == 'pull_request'
        run: |
          git config --local user.email "vnagaraj984@gmail.com"
          git config --local user.name "nag9844"

          # Generate docs
          terraform-docs .

          # Always add README.md if it exists (it should after terraform-docs)
          if [ -f README.md ]; then
            git add README.md
            # Attempt to commit. If no changes, this command will do nothing.
            git commit -m "docs: Update README.md" || true
          fi

      - name: Terraform Plan and Commit
        id: plan
        if: github.event_name == 'pull_request'
        run: |
          git config --local user.email "vnagaraj984@gmail.com"
          git config --local user.name "nag9844"

          terraform plan -no-color -input=false > plan.txt

          # Always add plan.txt if it exists
          if [ -f plan.txt ]; then
            git add plan.txt
            # Attempt to commit. If no changes, this command will do nothing.
            git commit -m "chore: Update plan.txt" || true
          fi

      - name: Push generated changes
        if: github.event_name == 'pull_request'
        run: |
          # Only pull and push if there are any new commits to push (from this workflow)
          # Check if there are local commits not yet on remote
          # This avoids pulling/pushing if no docs or plan changes were made
          if ! git diff --quiet origin/${{ github.head_ref }}; then
            echo "Local changes detected. Performing pull --rebase and push."
            git pull --rebase origin ${{ github.head_ref }} # Pull changes from the PR branch
            git push origin HEAD:${{ github.head_ref }}     # Push the rebased changes
          else
            echo "No changes to push from this workflow."
          fi

      - name: Update Pull Request Comment
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN_OUTPUT: ${{ steps.plan.outputs.stdout }} # This will be empty, read from file instead
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            let planContent = '';
            try {
              planContent = fs.readFileSync('plan.txt', 'utf8');
            } catch (error) {
              console.log('plan.txt not found, possibly no changes or plan failed.');
              planContent = 'No plan output available or plan failed to generate.';
            }

            const output = `#### Terraform Format and Style \`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization \`${{ steps.init.outcome }}\`
            #### Terraform Validation \`${{ steps.validate.outcome }}\`
            #### Terraform Plan \`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`hcl
            ${planContent}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure' && github.event_name == 'pull_request' # Only fail PR if plan fails
        run: exit 1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false