name: AWS infra
 
on:
  pull_request:
    branches: [main]    # trigger only on PR to main
 
permissions:
  id-token: write
  contents: read
  pull-requests: write  # to add comment on PR
 
jobs:
  lint-and-security:
    name: Lint and Security Checks
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Install TFLint
        run: |
wget https://github.com/terraform-linters/tflint/releases/download/v0.50.2/tflint_linux_amd64.zip
unzip tflint_linux_amd64.zip
          sudo mv tflint /usr/local/bin/
          tflint --version
 
      - name: Run TFLint
        run: tflint --init && tflint -f compact
        working-directory: ./
 
      - name: Install Checkov
        run: pip install checkov
 
      - name: Run Checkov with soft fail
        run: checkov --directory . --soft-fail
 
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: lint-and-security
 
    env:
      AWS_REGION: ${{ secrets.AWS_REGION || 'ap-south-1' }}
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::199570228070:role/oidc-demo-role
          aws-region: ${{ env.AWS_REGION }}
 
      - name: Format Terraform code
        run: terraform fmt -recursive
 
      - name: Initialize Terraform
        run: terraform init
 
      - name: Validate Terraform
        run: terraform validate
 
      - name: Terraform Plan
        run: |
          terraform plan -no-color -out=tfplan.binary | tee plan.txt
 
- name: Create plan summary as README.md
        run: |
             echo '## Terraform Plan Summary' > readme.md
             echo '```hcl' >> readme.md
             cat plan.txt >> readme.md
             echo '```' >> readme.md
 
- name: Upload plan.md artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-summary
path: readme.md
 
      - name: Comment on PR with plan summary
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
path: readme.md